-- liquibase formatted sql

-- changeset bmisa:1749385613301-1
CREATE TABLE achievements
(
    achievement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id          BIGINT                                  NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    experiencepoints INTEGER,
    CONSTRAINT pk_achievements PRIMARY KEY (achievement_id)
);

-- changeset bmisa:1749385613301-2
CREATE TABLE addons
(
    addon_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id  BIGINT                                  NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    price    DECIMAL                                 NOT NULL,
    type     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_addons PRIMARY KEY (addon_id)
);

-- changeset bmisa:1749385613301-3
CREATE TABLE games
(
    game_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    genre_id    BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    rating      INTEGER,
    price       DECIMAL                                 NOT NULL,
    releasedate date                                    NOT NULL,
    publisher   VARCHAR(255),
    CONSTRAINT pk_games PRIMARY KEY (game_id)
);

-- changeset bmisa:1749385613301-4
CREATE TABLE genres
(
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (genre_id)
);

-- changeset bmisa:1749385613301-5
CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

-- changeset bmisa:1749385613301-6
CREATE TABLE user_achievements
(
    userachievement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    achievement_id     BIGINT                                  NOT NULL,
    unlock_date        date                                    NOT NULL,
    CONSTRAINT pk_user_achievements PRIMARY KEY (userachievement_id)
);

-- changeset bmisa:1749385613301-7
CREATE TABLE user_addons
(
    useraddon_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    addon_id      BIGINT                                  NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    purchase_date date                                    NOT NULL,
    CONSTRAINT pk_user_addons PRIMARY KEY (useraddon_id)
);

-- changeset bmisa:1749385613301-8
CREATE TABLE user_games
(
    usergame_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    game_id       BIGINT                                  NOT NULL,
    purchase_date date                                    NOT NULL,
    CONSTRAINT pk_user_games PRIMARY KEY (usergame_id)
);

-- changeset bmisa:1749385613301-9
CREATE TABLE user_genres
(
    usergenre_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    genre_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_genres PRIMARY KEY (usergenre_id)
);

-- changeset bmisa:1749385613301-10
CREATE TABLE users
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    age              INTEGER                                 NOT NULL,
    balance          DECIMAL                                 NOT NULL,
    experiencepoints INTEGER                                 NOT NULL,
    role_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- changeset bmisa:1749385613301-11
ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

-- changeset bmisa:1749385613301-12
ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

-- changeset bmisa:1749385613301-13
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset bmisa:1749385613301-14
ALTER TABLE achievements
    ADD CONSTRAINT FK_ACHIEVEMENTS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (game_id);

-- changeset bmisa:1749385613301-15
ALTER TABLE addons
    ADD CONSTRAINT FK_ADDONS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (game_id);

-- changeset bmisa:1749385613301-16
ALTER TABLE games
    ADD CONSTRAINT FK_GAMES_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genres (genre_id);

-- changeset bmisa:1749385613301-17
ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id);

-- changeset bmisa:1749385613301-18
ALTER TABLE user_achievements
    ADD CONSTRAINT FK_USER_ACHIEVEMENTS_ON_ACHIEVEMENT FOREIGN KEY (achievement_id) REFERENCES achievements (achievement_id);

-- changeset bmisa:1749385613301-19
ALTER TABLE user_achievements
    ADD CONSTRAINT FK_USER_ACHIEVEMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset bmisa:1749385613301-20
ALTER TABLE user_addons
    ADD CONSTRAINT FK_USER_ADDONS_ON_ADDON FOREIGN KEY (addon_id) REFERENCES addons (addon_id);

-- changeset bmisa:1749385613301-21
ALTER TABLE user_addons
    ADD CONSTRAINT FK_USER_ADDONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset bmisa:1749385613301-22
ALTER TABLE user_games
    ADD CONSTRAINT FK_USER_GAMES_ON_GAME FOREIGN KEY (game_id) REFERENCES games (game_id);

-- changeset bmisa:1749385613301-23
ALTER TABLE user_games
    ADD CONSTRAINT FK_USER_GAMES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- changeset bmisa:1749385613301-24
ALTER TABLE user_genres
    ADD CONSTRAINT FK_USER_GENRES_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genres (genre_id);

-- changeset bmisa:1749385613301-25
ALTER TABLE user_genres
    ADD CONSTRAINT FK_USER_GENRES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

-- Создаем расширение (должно быть первым)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Индексы для users
CREATE INDEX IF NOT EXISTS idx_users_hash_email ON users USING hash(email);

-- Индексы для user_games
CREATE INDEX IF NOT EXISTS idx_usergames_user_game ON user_games(user_id, game_id);
CREATE INDEX IF NOT EXISTS idx_usergames_brin_date ON user_games USING brin(purchase_date);

-- Индексы для achievements
CREATE INDEX IF NOT EXISTS idx_achievements_highxp ON achievements(experiencepoints)
    WHERE experiencepoints > 50;

-- Индекс для games
CREATE INDEX IF NOT EXISTS idx_games_name_gin ON games USING GIN (name gin_trgm_ops);

INSERT INTO roles (role_id, name) VALUES (1, 'PLAYER') ON CONFLICT DO NOTHING;
INSERT INTO roles (role_id, name) VALUES (2, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (role_id, name) VALUES (3, 'GAMEMANAGER') ON CONFLICT DO NOTHING;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

insert into "users" ("name", "email", "password", "role_id", "age", "balance", "experiencepoints") values
                                                                                                       ('Thegre', 'aibaa@example.com', crypt('123', gen_salt('bf', 10)), 1, 25, 100.00, 0),
                                                                                                       ('Mekeken4', 'hex7@example.com', crypt('123', gen_salt('bf', 10)), 1, 30, 150.50, 0),
                                                                                                       ('Teteggeo', 'tetr67@example.com', crypt('123', gen_salt('bf', 10)), 1, 16, 70.50, 0),
                                                                                                       ('Blebb', 'blebb7@example.com', crypt('123', gen_salt('bf', 10)), 1, 15, 40, 0),
                                                                                                       ('aiaiaiaiaa', 'lelelel@example.com', crypt('123', gen_salt('bf', 10)), 1, 18, 50.75, 0),
                                                                                                       ('Ifgen56', 'Guruga532@gmail.com', crypt('123', gen_salt('bf', 10)), 1, 14, 5, 0);

insert into "genres" ("name") values
                                  ('Action'),
                                  ('RPG'),
                                  ('Puzzles'),
                                  ('Strategy'),
                                  ('Simulator'),
                                  ('Tower_defence'),
                                  ('Adventure'),
                                  ('MOBA'),
                                  ('Roguelike');

insert into "games" ("genre_id", "name", "rating", "price", "releasedate", "publisher") values
                                                                                            (2, 'Assassin`s Creed Origin', 16, 59.99, '2018-05-10', 'Ubisoft'),
                                                                                            (9, 'Fallout 4', 18, 49.99, '2015-11-15', 'Bethesda'),
                                                                                            (3, 'Funny puzzles', 12, 19.99, '2021-08-21', 'Alen'),
                                                                                            (4, 'Hearts of Iron 4', 18, 39.99, '2020-02-10', 'Paradox Interactive'),
                                                                                            (5, 'Powerlifter simulator', 14, 4.99, '2023-02-01', 'Robobox'),
                                                                                            (8, 'Deadlock', 16, 0, '2024-03-02', 'Valve'),
                                                                                            (9, 'Risk of Rain', 14, 9.99, '2018-05-04', 'Hopoo');

insert into "addons" ("game_id", "name", "price", "type") values
                                                              (1, 'Max level bundle', 9.99, 'IN_GAME_PURCHASE'),
                                                              (4, 'Gotterdamerrung', 5.99, 'DLC'),
                                                              (1, 'Golden horse', 6.99, 'IN_GAME_PURCHASE'),
                                                              (4, 'Graveyard of empires', 7.99, 'DLC'),
                                                              (7, 'Survivors of the Void', 5.99, 'DLC');

insert into "achievements" ("game_id", "name", "experiencepoints") values
                                                                       (1, 'Last assassin', 50),
                                                                       (4, 'Destroyer of Worlds', 30),
                                                                       (4, 'History repeated itself', 75),
                                                                       (3, 'Pretty collector', 60),
                                                                       (7, 'Full complete', 100),
                                                                       (5, 'Heavy heavy', 55);

insert into "user_games" ("user_id", "game_id", "purchase_date") values
                                                                     (1, 1, '2024-01-05'),
                                                                     (1, 2, '2024-02-12'),
                                                                     (2, 3, '2024-03-20'),
                                                                     (3, 4, '2025-01-01'),
                                                                     (4, 5, '2025-02-03'),
                                                                     (4, 6, '2025-02-03'),
                                                                     (4, 7, '2025-02-03'),
                                                                     (5, 7, '2025-02-08'),
                                                                     (6, 4, '2025-03-01');

insert into "user_achievements" ("user_id", "achievement_id","unlock_date") values
                                                                                (3, 2,'2025-03-01'),
                                                                                (3, 3, '2025-03-02'),
                                                                                (4, 5, '2025-03-03'),
                                                                                (5, 5, '2025-03-06'),
                                                                                (4, 6, '2025-03-09');

insert into "user_addons" ("user_id", "addon_id", "purchase_date") values
                                                                       (3, 2, '2024-03-20'),
                                                                       (4, 5, '2025-02-05'),
                                                                       (1, 1, '2024-09-01'),
                                                                       (6, 2, '2025-01-01');

insert into user_genres ("user_id", "genre_id") values
                                                    (1,2),
                                                    (1,4),
                                                    (2,5),
                                                    (4,8),
                                                    (3,5),
                                                    (1,7),
                                                    (5,2),
                                                    (5,3),
                                                    (6,1),
                                                    (6,3),
                                                    (6,6);

UPDATE users u
SET experiencepoints = COALESCE((
                                    SELECT SUM(a.experiencepoints)
                                    FROM user_achievements ua
                                             JOIN achievements a ON ua.achievement_id = a.achievement_id
                                    WHERE ua.user_id = u.user_id
                                ), 0);

